### ISSUE TITLE
PHP Fatal error:  Cannot redeclare getModelForGuard()

### ISSUE THREAD

**Issue by danishjamil** [artkonekt/acl#1]
Hi,

I'm getting the following issue  when using spatie/laravel-permission and vanillo/framework

PHP Fatal error:  Cannot redeclare getModelForGuard() (previously declared in C:\....\vendor\konekt\acl\src\Support\helpers.php:8) in C:\....\vendor\spatie\laravel-permission\src\helpers.php on line 14

**Comment by fulopattila122** [comment]
Are you using both Spatie's ACL and this one?

**Comment by fulopattila122** [comment]
This is a duplicate of vanilophp/framework#9
